[deployment]

docker = false
port = 8080
db_path = "~/Documents/databases/feederizer.db"

[theme]

borderColor = "#800080"
textColor = "#F5F5DC"
textHighlight = "#800080"
titleColor = "#4B0082"
titleTextColor = "#F5F5DC"
