
[authentication]
  asddfdfautoLogin = true
  pass = "c2FkZg=="
  user = "jakc"

[deployment]
  db_path = "~/Documents/databases/feederizer.db"
  docker = false
  port = 8080

[theme]
  borderColor = "#800080"
  textColor = "#F5F5DC"
  textHighlight = "#5B0082"
  titleColor = "#4B0082"
  titleTextColor = "#F5F5DC"
