version: '3.8'

services:
  app:
    image: feederizer_server:1.0
    build: .
    container_name: feederizer
    volumes:
      - /home/jdzialo/Documents/databases/feederizer.db:/data/feederizer.db:z
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
